using System;
using System.Collections.Generic;
using System.IO;
using System.Text.Json;
using ES2Access.Core.Speech;
using Xunit;

namespace ES2Access.Tests.Speech
{
    /// <summary>
    /// The cue cursor a cutscene reads its descriptions through, and the shipped table it reads
    /// them from. The table is the committed one, regenerated by build-descriptions.ps1 from an
    /// authoring folder that lives outside the repository, so what is checked here is what a bad
    /// regeneration or a hand edit would break: a track whose cues run backwards would speak out
    /// of order, an outro that lost its variant suffix would describe the wrong ending's gaps,
    /// and a cue that overran its slot would talk over the video's own dialogue.
    /// </summary>
    public class VideoDescriptionsTests
    {
        private static DescriptionTrack Track(params float[] times)
        {
            DescriptionCue[] cues = new DescriptionCue[times.Length];
            for (int i = 0; i < times.Length; i++)
            {
                cues[i] = new DescriptionCue(times[i], "cue " + i);
            }

            return new DescriptionTrack(cues);
        }

        private static List<string> Drain(DescriptionTrack track, float playTime)
        {
            List<string> said = new List<string>();
            string line;
            while (track.TryNext(playTime, out line))
            {
                said.Add(line);
            }

            return said;
        }

        [Fact]
        public void SaysNothingBeforeTheFirstCueIsDue()
        {
            DescriptionTrack track = Track(1f, 4.5f);
            Assert.Empty(Drain(track, 0.9f));
            Assert.False(track.Finished);
        }

        [Fact]
        public void SaysACueTheMomentItsTimeArrives()
        {
            DescriptionTrack track = Track(1f, 4.5f);
            Assert.Equal(new[] { "cue 0" }, Drain(track, 1f));
        }

        [Fact]
        public void SaysEachCueOnce()
        {
            DescriptionTrack track = Track(1f, 4.5f);
            Assert.Single(Drain(track, 2f));
            Assert.Empty(Drain(track, 3f));
            Assert.Single(Drain(track, 5f));
        }

        [Fact]
        public void DrainsEveryCueALateFramePassedOver()
        {
            // The frame that arrives at 5 seconds owes the player both of the cues before it, in
            // the order they were written.
            DescriptionTrack track = Track(1f, 4.5f, 9f);
            Assert.Equal(new[] { "cue 0", "cue 1" }, Drain(track, 5f));
            Assert.False(track.Finished);
        }

        [Fact]
        public void IsFinishedOnceEveryCueHasBeenHandedOut()
        {
            DescriptionTrack track = Track(1f, 4.5f);
            Drain(track, 99f);
            Assert.True(track.Finished);
            Assert.Empty(Drain(track, 99f));
        }

        [Fact]
        public void RewindingPlaysTheTrackAgain()
        {
            DescriptionTrack track = Track(1f, 4.5f);
            Assert.Equal(2, Drain(track, 99f).Count);
            track.Rewind();
            Assert.Equal(2, Drain(track, 99f).Count);
        }

        [Fact]
        public void AnEmptyTrackIsFinishedAndSilent()
        {
            DescriptionTrack track = new DescriptionTrack(null);
            Assert.Equal(0, track.Count);
            Assert.True(track.Finished);
            Assert.Empty(Drain(track, 99f));
        }

        [Fact]
        public void AnOutroPrefersTheTrackWrittenForItsEnding()
        {
            using (Table(
                Cues("Cravers_Outro", 1f),
                Cues("Cravers_Outro.LostBack", 2f),
                Cues("Cravers_Outro.LostNotBack", 3f, 4f)))
            {
                Assert.Equal(1, VideoDescriptions.Track("Cravers_Outro", "LostBack").Count);
                Assert.Equal(2, VideoDescriptions.Track("Cravers_Outro", "LostNotBack").Count);
            }
        }

        [Fact]
        public void AnEndingWithNoTrackOfItsOwnFallsBackToTheVideos()
        {
            using (Table(Cues("Cravers_Outro", 1f, 2f)))
            {
                Assert.Equal(2, VideoDescriptions.Track("Cravers_Outro", "LostBack").Count);
            }
        }

        [Fact]
        public void AVideoNobodyWroteForHasNoTrack()
        {
            using (Table(Cues("Swamp", 1f)))
            {
                Assert.Null(VideoDescriptions.Track("Metaplot_LostBack", null));
                Assert.Null(VideoDescriptions.Track(null, null));
                Assert.Null(VideoDescriptions.Track("", null));
            }
        }

        [Fact]
        public void WithNoTableNothingIsDescribed()
        {
            VideoDescriptions.Reset();
            Assert.Equal(0, VideoDescriptions.Count);
            Assert.Null(VideoDescriptions.Track("Swamp", null));
        }

        [Fact]
        public void EachPlaybackGetsACursorOfItsOwn()
        {
            // The same colonization scene plays again the next time a colony ship lands.
            using (Table(Cues("Swamp", 1f, 2f)))
            {
                DescriptionTrack first = VideoDescriptions.Track("Swamp", null);
                Drain(first, 99f);
                Assert.True(first.Finished);

                DescriptionTrack second = VideoDescriptions.Track("Swamp", null);
                Assert.False(second.Finished);
                Assert.Equal(2, Drain(second, 99f).Count);
            }
        }

        [Fact]
        public void TheShippedTableIsWellFormed()
        {
            string path = Path.Combine(TestPaths.Descriptions(), "english.json");
            Assert.True(File.Exists(path), "no english.json: the shipped description table is missing");

            using (JsonDocument document = JsonDocument.Parse(File.ReadAllText(path)))
            {
                Assert.Equal(JsonValueKind.Object, document.RootElement.ValueKind);
                int tracks = 0;

                foreach (JsonProperty entry in document.RootElement.EnumerateObject())
                {
                    tracks++;
                    Assert.Equal(entry.Name, entry.Name.Trim());
                    Assert.Equal(JsonValueKind.Array, entry.Value.ValueKind);

                    // An outro is the only video whose narration branches, and its gaps move with
                    // the branch, so it may never be keyed by the bare video name.
                    if (entry.Name.Contains("_Outro"))
                    {
                        Assert.True(
                            entry.Name.EndsWith(".LostBack") || entry.Name.EndsWith(".LostNotBack"),
                            entry.Name + ": an outro track with no ending on it"
                        );
                    }

                    double previous = -1;
                    double previousEnd = -1;
                    int cues = 0;
                    foreach (JsonElement cue in entry.Value.EnumerateArray())
                    {
                        cues++;
                        double at = cue.GetProperty("at").GetDouble();
                        double end = cue.GetProperty("end").GetDouble();
                        string text = cue.GetProperty("text").GetString();

                        Assert.True(at >= 0, entry.Name + ": a cue before the video starts");
                        Assert.True(at >= previous, entry.Name + ": cues out of order at " + at);
                        Assert.False(
                            string.IsNullOrWhiteSpace(text),
                            entry.Name + ": an empty description at " + at
                        );

                        // Nothing at runtime reads the end, so this is the only place a cue
                        // written longer than the gap it sits in is caught.
                        Assert.True(
                            end >= at,
                            entry.Name + ": a cue at " + at + " that ends before it is spoken"
                        );
                        Assert.True(
                            at >= previousEnd,
                            entry.Name + ": a cue at " + at + " that starts before the one before it ends"
                        );

                        previous = at;
                        previousEnd = end;
                    }

                    Assert.True(cues > 0, entry.Name + ": a track with no cues");
                }

                Assert.True(tracks > 0, "the shipped table describes nothing");
            }
        }

        /// <summary>Installs a table and takes it away again, so one test's videos are not still
        /// loaded during the next - <see cref="VideoDescriptions"/> is process-wide, the way it is
        /// in the game.</summary>
        private static IDisposable Table(params KeyValuePair<string, DescriptionCue[]>[] tracks)
        {
            Dictionary<string, DescriptionCue[]> table = new Dictionary<string, DescriptionCue[]>();
            foreach (KeyValuePair<string, DescriptionCue[]> track in tracks)
            {
                table[track.Key] = track.Value;
            }

            VideoDescriptions.Install(table);
            return new Installed();
        }

        private static KeyValuePair<string, DescriptionCue[]> Cues(string movie, params float[] times)
        {
            DescriptionCue[] cues = new DescriptionCue[times.Length];
            for (int i = 0; i < times.Length; i++)
            {
                cues[i] = new DescriptionCue(times[i], movie + " " + i);
            }

            return new KeyValuePair<string, DescriptionCue[]>(movie, cues);
        }

        private sealed class Installed : IDisposable
        {
            public void Dispose()
            {
                VideoDescriptions.Reset();
            }
        }
    }
}
